### ISSUE TITLE
Need better icons and UI for my product

### ISSUE THREAD

**Issue by gileli121** [Gitoffthelawn/Contact-Gitoffthelawn#4]
Hello,
I really need better icons for 
https://github.com/gileli121/WindowTop

I need to improve this:
![image](https://user-images.githubusercontent.com/17680514/85787879-bd47c080-b734-11ea-9f3f-45a4057af636.png)

Please send me a PSD file.

You will get paid. 
We can decide about the payment.
Let me know if you are interested to help.

**Comment by Gitoffthelawn** [comment]
Hello Gil!

That sounds good.

It's an interesting challenge because the size is very limited and every icon needs to be quickly discernible.

I have a couple ideas that I will need to further develop into a plan.

Aero is going to be quite a challenge because not everyone even knows what Aero means. It will be an interesting challenge to visually represent the impact of the user pressing that button.

Are there any restrictions as to the shape of each icon?  Can the icons have rounded corners or even be circles/ovals?

Are there specific dimensions required?

What color depth do you need?

**Comment by gileli121** [comment]
Hi, thanks for coming back to me.

Please contact me on gileli121@gmail.com
I want to discuss it with you in private

**Comment by Gitoffthelawn** [comment]
You're welcome.

I'll have some open time within the next few days, and I will email you then.

In the meantime, I will be thinking of ideas.

**Comment by gileli121** [comment]
Great.

About the name "Aero", You are welcome to name it differently.
I also not sure that this name is fine. I am open to renaming the name of the feature if it is not clear

We will talk about the low-level details on email.

**Comment by gileli121** [comment]
Nothing happened until now.
Closing.
